
_langs = {
        'Russian':              'ru',
        'English':              'en',
        'Afrikaans':            'af',
        'Arabic':               'ar',
        'Bulgarian':            'bg',
        'Bengali':              'bn',
        'Bosnian':              'bs',
        'Catalan':              'ca',
        'Czech':                'cs',
        'Welsh':                'cy',
        'Danish':               'da',
        'German':               'de',
        'Greek':                'el',
        'Esperanto':            'eo',
        'Spanish':              'es',
        'Estonian':             'et',
        'Finnish':              'fi',
        'French':               'fr',
        'Gujarati':             'gu',
        'Hindi':                'hi',
        'Croatian':             'hr',
        'Hungarian':            'hu',
        'Armenian':             'hy',
        'Indonesian':           'id',
        'Icelandic':            'is',
        'Italian':              'it',
        'Hebrew':               'iw',
        'Japanese':             'ja',
        'Javanese':             'jw',
        'Khmer':                'km',
        'Kannada':              'kn',
        'Korean':               'ko',
        'Latin':                'la',
        'Latvian':              'lv',
        'Macedonian':           'mk',
        'Malay':                'ms',
        'Malayalam':            'ml',
        'Marathi':              'mr',
        'Myanmar (Burmese)':    'my',
        'Nepali':               'ne',
        'Dutch':                'nl',
        'Norwegian':            'no',
        'Polish':               'pl',
        'Portuguese':           'pt',
        'Romanian':             'ro',
        'Sinhala':              'si',
        'Slovak':               'sk',
        'Albanian':             'sq',
        'Serbian':              'sr',
        'Sundanese':            'su',
        'Swedish':              'sv',
        'Swahili':              'sw',
        'Tamil':                'ta',
        'Telugu':               'te',
        'Thai':                 'th',
        'Filipino':             'tl',
        'Turkish':              'tr',
        'Ukrainian':            'uk',
        'Urdu':                 'ur',
        'Vietnamese':           'vi',
        'Chinese':              'zh-CN',
    }

languages = [lang for lang in _langs.keys()]
language_default = _langs.get('Russian')
